package com.elmrabti.entity;
// Generated Apr 26, 2021 12:50:47 AM by Hibernate Tools 4.3.1



/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private String codeClient;
     private String nomClient;
     private String adresseClient;

    public Client() {
    }

    public Client(String codeClient, String nomClient, String adresseClient) {
       this.codeClient = codeClient;
       this.nomClient = nomClient;
       this.adresseClient = adresseClient;
    }
   
    public String getCodeClient() {
        return this.codeClient;
    }
    
    public void setCodeClient(String codeClient) {
        this.codeClient = codeClient;
    }
    public String getNomClient() {
        return this.nomClient;
    }
    
    public void setNomClient(String nomClient) {
        this.nomClient = nomClient;
    }
    public String getAdresseClient() {
        return this.adresseClient;
    }
    
    public void setAdresseClient(String adresseClient) {
        this.adresseClient = adresseClient;
    }




}


