package com.elmrabti.entity;
// Generated Apr 26, 2021 12:50:47 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Operation generated by hbm2java
 */
public class Operation  implements java.io.Serializable {


     private Integer numOperation;
     private int numCompte;
     private Date dateOperation;
     private double montantMouvement;
     private String typeMouvement;

    public Operation() {
    }

    public Operation(int numCompte, Date dateOperation, double montantMouvement, String typeMouvement) {
       this.numCompte = numCompte;
       this.dateOperation = dateOperation;
       this.montantMouvement = montantMouvement;
       this.typeMouvement = typeMouvement;
    }
   
    public Integer getNumOperation() {
        return this.numOperation;
    }
    
    public void setNumOperation(Integer numOperation) {
        this.numOperation = numOperation;
    }
    public int getNumCompte() {
        return this.numCompte;
    }
    
    public void setNumCompte(int numCompte) {
        this.numCompte = numCompte;
    }
    public Date getDateOperation() {
        return this.dateOperation;
    }
    
    public void setDateOperation(Date dateOperation) {
        this.dateOperation = dateOperation;
    }
    public double getMontantMouvement() {
        return this.montantMouvement;
    }
    
    public void setMontantMouvement(double montantMouvement) {
        this.montantMouvement = montantMouvement;
    }
    public String getTypeMouvement() {
        return this.typeMouvement;
    }
    
    public void setTypeMouvement(String typeMouvement) {
        this.typeMouvement = typeMouvement;
    }




}


